# Site settings
title: Alisa Palson
email: palson@alisa.codes
description: > # this means to ignore newlines until "baseurl:"
  Alisa is a software developer in Tempe, AZ. She loves data visualization and cats.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alisa.codes" # the base hostname & protocol for your site
twitter_username: alisamfp
github_username:  alisamfp
# Build settings
markdown: kramdown
highlighter: rouge